### ISSUE TITLE
1.18.2 Forge Crash Path not associated with default file system

### ISSUE THREAD

**Issue by firemaster1294** [webbukkit/DynmapBlockScan#76]
Hi! I've been trying to use this scanner for a large mod pack I've been playing and it always seems to crash at Immersive Engineering, giving the error "Path not associated with default file system." Here's my log:

<details>
<summary>Log Data</summary>

[27.02 03:39:58] [Server] [Server thread/INFO] [DynmapBlockScan/]: [DynmapBlockScan] modid: immersiveengineering, src=/mods/ImmersiveEngineering-1.18.2-8.4.0-161.jar, cnt=3545
[27.02 03:39:58] [Server] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Path not associated with default file system.
[27.02 03:39:58] [Server] 	Index11
[27.02 03:39:58] [Server] 	Listeners:
[27.02 03:39:58] [Server] 		HIGH
[27.02 03:39:58] [Server] 		ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
[27.02 03:39:58] [Server] 		NORMAL
[27.02 03:39:58] [Server] 		ASM: chanceCubes.CCubesCore@9d6fd2d serverStart(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
[27.02 03:39:58] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$4157/0x000000080178e448@6f0f257b
[27.02 03:39:58] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$4157/0x000000080178e448@5d7a4cb6
[27.02 03:39:58] [Server] 		ASM: com.mcwlights.kikoz.MacawsLights@6bd96d80 onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
[27.02 03:39:58] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$4157/0x000000080178e448@1d5cb634
[27.02 03:39:58] [Server] 		ASM: com.mcwpaths.kikoz.MacawsPaths@71c719d onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
[27.02 03:39:58] [Server] 		ASM: class com.finallion.graveyard.init.TGSpawner onWorldLoad(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
[27.02 03:39:58] [Server] 		ASM: class com.finallion.graveyard.events.TGServerEvents onServerStart(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
[27.02 03:39:58] [Server] 		ASM: org.dynmapblockscan.forge_1_18.DynmapBlockScanMod@15162cc0 onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
[27.02 03:39:58] [Server] 		ASM: com.mcwbridges.kikoz.MacawsBridges@6a8a237d onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
[27.02 03:39:58] [Server] 		ASM: com.mcwfences.kikoz.MacawsFences@6cc8ba66 onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
[27.02 03:39:58] [Server] 		ASM: class mcp.mobius.waila.forge.ForgeWaila$Subscriber serverStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
[27.02 03:39:58] [Server] 		ASM: com.haoict.tiab.Tiab@734f5590 onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
[27.02 03:39:58] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$4157/0x000000080178e448@706bf2a5
[27.02 03:39:58] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$4157/0x000000080178e448@6659352e
[27.02 03:39:58] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$4157/0x000000080178e448@6949caaf
[27.02 03:39:58] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$4157/0x000000080178e448@115c2ca4
[27.02 03:39:58] [Server] 		ASM: pregenerator.common.manager.ServerManager@381e2880 onServerStarted(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
[27.02 03:39:58] [Server] java.lang.UnsupportedOperationExceptionPath not associated with default file system.
[27.02 03:39:58] [Server] 	at java.base/java.nio.file.Path.toFile(Path.java:771)
[27.02 03:39:58] [Server] 	at TRANSFORMER/dynmapblockscan@3.4-SNAPSHOT-229/org.dynmapblockscan.forge_1_18.DynmapBlockScanPlugin.buildAssetMap(DynmapBlockScanPlugin.java:64)
[27.02 03:39:58] [Server] 	at TRANSFORMER/dynmapblockscan@3.4-SNAPSHOT-229/org.dynmapblockscan.forge_1_18.DynmapBlockScanPlugin.serverStarting(DynmapBlockScanPlugin.java:78)
[27.02 03:39:58] [Server] 	at TRANSFORMER/dynmapblockscan@3.4-SNAPSHOT-229/org.dynmapblockscan.forge_1_18.DynmapBlockScanMod.onServerStarting(DynmapBlockScanMod.java:80)
[27.02 03:39:58] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler_254_DynmapBlockScanMod_onServerStarting_ServerStartingEvent.invoke(.dynamic)
[27.02 03:39:58] [Server] 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[27.02 03:39:58] [Server] 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[27.02 03:39:58] [Server] 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[27.02 03:39:58] [Server] 	at TRANSFORMER/forge@40.2.1/net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:98)
[27.02 03:39:58] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:207)
[27.02 03:39:58] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
[27.02 03:39:58] [Server] 	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
[27.02 03:39:58] [Server] 	at java.base/java.lang.Thread.run(Thread.java:833)
[27.02 03:39:58] [Server] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
[27.02 03:39:58] [Server] java.lang.UnsupportedOperationExceptionPath not associated with default file system.

</details>

**Comment by doosedev** [comment]
I can also reproduce this behavior using the 3.4-beta-5 release of BlockScan. I encountered a similar issue with Dynmap itself before the 3.5 update (something related to nested JARs iirc) so maybe that fix can be ported to BlockScan as well

**Comment by mikeprimm** [comment]
What Java VM version are you running - found reference to this error over on the oracle repos (https://github.com/oracle/graal/issues/1035 )

**Comment by XBagon** [comment]
I got this error as well using `DynmapBlockScan-3.5-beta-3-forge-1.18.jar` on java version `openjdk 17.0.6 2023-01-17`

**Comment by kasperbjerby** [comment]
Same here,
openjdk version "17.0.7" 2023-04-18 LTS
OpenJDK Runtime Environment Microsoft-7626293 (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Microsoft-7626293 (build 17.0.7+7-LTS, mixed mode, sharing)

**Comment by TheUnknownCod3r** [comment]
Can also confirm, trying to run on a server hosted by WinterNode, Java 17, 
        Java Version: 17.0.7, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium

**Comment by mikeprimm** [comment]
Obsolete build - probably should try https://dynmap.us/builds/DynmapBlockScan/DynmapBlockScan-3.5-beta-3-forge-1.18.jar

**Comment by TheUnknownCod3r** [comment]
> Obsolete build - probably should try https://dynmap.us/builds/DynmapBlockScan/DynmapBlockScan-3.5-beta-3-forge-1.18.jar

This is actually the one I tried, same issue.

**Comment by mikeprimm** [comment]
Running this VM and this build on 40.2.8 right now, without any issue - going to need more to reproduce

**Comment by TheUnknownCod3r** [comment]
> Running this VM and this build on 40.2.8 right now, without any issue - going to need more to reproduce

Crash Report: https://pastebin.com/4WpRqB37

I run just Dynmap first to make sure it loads and correct my config to the port I opened, Stop the server, add DynmapBlockScan, restart the server, and it starts checking modid's, then crashes.

**Comment by mikeprimm** [comment]
Try https://dynmap.us/builds/DynmapBlockScan/DynmapBlockScan-3.6-SNAPSHOT-forge-1.18.jar - more breakage from Forge's JarInJar changes

**Comment by TheUnknownCod3r** [comment]
> Try https://dynmap.us/builds/DynmapBlockScan/DynmapBlockScan-3.6-SNAPSHOT-forge-1.18.jar - more breakage from Forge's JarInJar changes

This one seems to work fine for me, no longer crashing and server initialises fully.
