### ISSUE TITLE
Crash on forge server 1.19.2

### ISSUE THREAD

**Issue by PavlychevV** [webbukkit/DynmapBlockScan#78]
Minecraft 1.19.2
Forge: 43.2.11 server
Mod: [DynmapBlockScan-3.4-beta-5-forge-1.19.jar](https://dynmap.us/builds/DynmapBlockScan/DynmapBlockScan-3.4-beta-5-forge-1.19.jar)
Java: Azul Zulu 17 LTS amd64

Without the Block Scan works perfectly. 

Mod list:
![Снимок экрана 2023-05-14 в 11 20 43](https://github.com/webbukkit/DynmapBlockScan/assets/44994888/e33d2184-1282-42a8-8c2d-a8c9c00583f8)

Crash log:
```[14May2023 11:14:42.533] [Server thread/INFO] [DynmapBlockScan/]: [DynmapBlockScan] Loading models....
[14May2023 11:14:42.549] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: org/dynmap/modsupport/BlockSide
	Index: 6
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
		2: NORMAL
		3: ASM: com.axedgaming.endersdelight.EndersDelight@4048c3ef onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
		4: ASM: class top.seraphjack.simplelogin.server.ServerLoader serverStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
		5: ASM: net.akaneo.fastfooddelight.FastFoodDelight@58186651 onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
		6: ASM: org.dynmapblockscan.forge_1_18.DynmapBlockScanMod@6336bbcd onServerStarting(Lnet/minecraftforge/event/server/ServerStartingEvent;)V
java.lang.NoClassDefFoundError: org/dynmap/modsupport/BlockSide
	at TRANSFORMER/dynmapblockscan@3.4-beta-5-233/org.dynmapblockscan.core.blockstate.ElementFace.<clinit>(ElementFace.java:7)
	at TRANSFORMER/dynmapblockscan@3.4-beta-5-233/org.dynmapblockscan.core.model.BlockElement$Deserializer.deserialize(BlockElement.java:123)
	at TRANSFORMER/dynmapblockscan@3.4-beta-5-233/org.dynmapblockscan.core.model.BlockElement$Deserializer.deserialize(BlockElement.java:105)
	at MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.Gson.fromJson(Gson.java:963)
	at TRANSFORMER/dynmapblockscan@3.4-beta-5-233/org.dynmapblockscan.core.AbstractBlockScanBase.loadBlockModelFile(AbstractBlockScanBase.java:301)
	at TRANSFORMER/dynmapblockscan@3.4-beta-5-233/org.dynmapblockscan.core.AbstractBlockScanBase.loadModels(AbstractBlockScanBase.java:1039)
	at TRANSFORMER/dynmapblockscan@3.4-beta-5-233/org.dynmapblockscan.forge_1_18.DynmapBlockScanPlugin.serverStarting(DynmapBlockScanPlugin.java:184)
	at TRANSFORMER/dynmapblockscan@3.4-beta-5-233/org.dynmapblockscan.forge_1_18.DynmapBlockScanMod.onServerStarting(DynmapBlockScanMod.java:80)
	at TRANSFORMER/dynmapblockscan@3.4-beta-5-233/org.dynmapblockscan.forge_1_18.__DynmapBlockScanMod_onServerStarting_ServerStartingEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.2.11/net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:104)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:199)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.dynmap.modsupport.BlockSide
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 23 more

[14May2023 11:14:42.550] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/dynmap/modsupport/BlockSide
	at org.dynmapblockscan.core.blockstate.ElementFace.<clinit>(ElementFace.java:7) ~[DynmapBlockScan-3.4-beta-5-forge-1.19.jar%23217!/:?]
	at org.dynmapblockscan.core.model.BlockElement$Deserializer.deserialize(BlockElement.java:123) ~[DynmapBlockScan-3.4-beta-5-forge-1.19.jar%23217!/:?]
	at org.dynmapblockscan.core.model.BlockElement$Deserializer.deserialize(BlockElement.java:105) ~[DynmapBlockScan-3.4-beta-5-forge-1.19.jar%23217!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar%2370!/:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar%2370!/:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.8.9.jar%2370!/:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar%2370!/:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[gson-2.8.9.jar%2370!/:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[gson-2.8.9.jar%2370!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2370!/:?]
	at org.dynmapblockscan.core.AbstractBlockScanBase.loadBlockModelFile(AbstractBlockScanBase.java:301) ~[DynmapBlockScan-3.4-beta-5-forge-1.19.jar%23217!/:?]
	at org.dynmapblockscan.core.AbstractBlockScanBase.loadModels(AbstractBlockScanBase.java:1039) ~[DynmapBlockScan-3.4-beta-5-forge-1.19.jar%23217!/:?]
	at org.dynmapblockscan.forge_1_18.DynmapBlockScanPlugin.serverStarting(DynmapBlockScanPlugin.java:184) ~[DynmapBlockScan-3.4-beta-5-forge-1.19.jar%23217!/:?]
	at org.dynmapblockscan.forge_1_18.DynmapBlockScanMod.onServerStarting(DynmapBlockScanMod.java:80) ~[DynmapBlockScan-3.4-beta-5-forge-1.19.jar%23217!/:?]
	at org.dynmapblockscan.forge_1_18.__DynmapBlockScanMod_onServerStarting_ServerStartingEvent.invoke(.dynamic) ~[DynmapBlockScan-3.4-beta-5-forge-1.19.jar%23217!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:104) ~[forge-1.19.2-43.2.11-universal.jar%23278!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:199) ~[server-1.19.2-20220805.130853-srg.jar%23273!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625) ~[server-1.19.2-20220805.130853-srg.jar%23273!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23273!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.dynmap.modsupport.BlockSide
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 23 more
```

**Comment by mikeprimm** [comment]
DynmapBlockScan requires Dynmap
